CREATE DATABASE IF NOT EXISTS CLINICAL_SENTINEL_DB;
USE DATABASE CLINICAL_SENTINEL_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE DIM_FACILITIES (
    FACILITY_ID INT PRIMARY KEY,
    FACILITY_NAME VARCHAR(100),
    REGION VARCHAR(50),
    COMPLIANCE_STATUS VARCHAR(20)
);

CREATE OR REPLACE TABLE DIM_PROVIDERS (
    PROVIDER_ID INT PRIMARY KEY,
    PROVIDER_NAME VARCHAR(100),
    ROLE VARCHAR(50),
    HIRE_DATE DATE
);

CREATE OR REPLACE TABLE FACT_SERVICE_LOGS (
    LOG_ID INT PRIMARY KEY,
    FACILITY_ID INT,
    PROVIDER_ID INT,
    SERVICE_DATE DATE,
    SERVICE_HOURS DECIMAL(5,2),
    HIPAA_SIGNATURE_CAPTURED BOOLEAN,
    FOREIGN KEY (FACILITY_ID) REFERENCES DIM_FACILITIES(FACILITY_ID),
    FOREIGN KEY (PROVIDER_ID) REFERENCES DIM_PROVIDERS(PROVIDER_ID)
);

CREATE OR REPLACE VIEW VW_COMPLIANCE_REPORT AS
SELECT 
    L.LOG_ID,
    L.SERVICE_DATE,
    F.FACILITY_NAME,
    P.PROVIDER_NAME,
    L.SERVICE_HOURS,
    L.HIPAA_SIGNATURE_CAPTURED
FROM FACT_SERVICE_LOGS L
LEFT JOIN DIM_FACILITIES F ON L.FACILITY_ID = F.FACILITY_ID
LEFT JOIN DIM_PROVIDERS P ON L.PROVIDER_ID = P.PROVIDER_ID;