SELECT 
    L.LOG_ID, 
    F.FACILITY_NAME, 
    L.SERVICE_DATE 
FROM CLINICAL_SENTINEL_DB.PUBLIC.FACT_SERVICE_LOGS L
LEFT JOIN CLINICAL_SENTINEL_DB.PUBLIC.DIM_FACILITIES F ON L.FACILITY_ID = F.FACILITY_ID
WHERE L.SERVICE_HOURS IS NULL;

SELECT 
    L.LOG_ID, 
    P.PROVIDER_NAME, 
    L.SERVICE_DATE 
FROM CLINICAL_SENTINEL_DB.PUBLIC.FACT_SERVICE_LOGS L
LEFT JOIN CLINICAL_SENTINEL_DB.PUBLIC.DIM_PROVIDERS P ON L.PROVIDER_ID = P.PROVIDER_ID
WHERE L.HIPAA_SIGNATURE_CAPTURED = FALSE;

SELECT 
    LOG_ID, 
    SERVICE_DATE 
FROM CLINICAL_SENTINEL_DB.PUBLIC.FACT_SERVICE_LOGS 
WHERE SERVICE_DATE > CURRENT_DATE();