SELECT 
    COALESCE(COUNT(*), 0) AS TOTAL_LOGS,
    COALESCE(SUM(CASE WHEN HIPAA_SIGNATURE_CAPTURED = TRUE THEN 1 ELSE 0 END), 0) AS COMPLIANT_LOGS,
    COALESCE(SUM(CASE WHEN HIPAA_SIGNATURE_CAPTURED = FALSE OR HIPAA_SIGNATURE_CAPTURED IS NULL THEN 1 ELSE 0 END), 0) AS NON_COMPLIANT_LOGS,
    COALESCE(
        ROUND(
            (SUM(CASE WHEN HIPAA_SIGNATURE_CAPTURED = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)) * 100, 
            2
        ), 0
    ) AS COMPLIANCE_RATE_PERCENT
FROM CLINICAL_SENTINEL_DB.PUBLIC.VW_COMPLIANCE_REPORT;