CREATE ROLE IF NOT EXISTS POWERBI_REPORTING_ROLE;

GRANT USAGE ON DATABASE CLINICAL_SENTINEL_DB TO ROLE POWERBI_REPORTING_ROLE;
GRANT USAGE ON SCHEMA CLINICAL_SENTINEL_DB.PUBLIC TO ROLE POWERBI_REPORTING_ROLE;
GRANT SELECT ON VIEW CLINICAL_SENTINEL_DB.PUBLIC.VW_COMPLIANCE_REPORT TO ROLE POWERBI_REPORTING_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE POWERBI_REPORTING_ROLE;

GRANT ROLE POWERBI_REPORTING_ROLE TO USER REESEPETERSEN;