INSERT INTO CLINICAL_SENTINEL_DB.PUBLIC.FACT_SERVICE_LOGS 
(LOG_ID, FACILITY_ID, PROVIDER_ID, SERVICE_DATE, SERVICE_HOURS, HIPAA_SIGNATURE_CAPTURED) 
VALUES (999, 1, 101, '2026-06-05', NULL, FALSE);

SELECT * FROM CLINICAL_SENTINEL_DB.PUBLIC.FACT_SERVICE_LOGS WHERE SERVICE_HOURS IS NULL;
SELECT * FROM CLINICAL_SENTINEL_DB.PUBLIC.FACT_SERVICE_LOGS WHERE HIPAA_SIGNATURE_CAPTURED = FALSE;

SELECT * FROM CLINICAL_SENTINEL_DB.PUBLIC.VW_COMPLIANCE_REPORT;

DELETE FROM CLINICAL_SENTINEL_DB.PUBLIC.FACT_SERVICE_LOGS WHERE LOG_ID = 999;